<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>934462a7-3b70-4f87-8cd5-55923e9bb24f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.logo_production_katalon > a > img[alt=&quot;Katalon&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_85550910293']/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ff4fbff3-b0c3-4347-822f-13813b0c0b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/logo_kat/katalon-logo-newbrand2022-top-nav.png</value>
      <webElementGuid>5dba7747-7ec6-4f2c-8592-edecb7b3822e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Katalon</value>
      <webElementGuid>28ec853e-28b3-4b13-a9fe-094d50a2886b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_85550910293&quot;)/div[@class=&quot;logo_production_katalon&quot;]/a[1]/img[1]</value>
      <webElementGuid>464213bb-2387-43c7-a512-74621b507546</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_85550910293']/div/a/img</value>
      <webElementGuid>e446947d-108f-43ec-8f8d-11e77ae68a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Katalon'])[4]</value>
      <webElementGuid>8fe55606-8ffa-4306-a834-d28cf7588555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/a/img</value>
      <webElementGuid>fe554ddb-e13a-4000-af95-375933d34e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/logo_kat/katalon-logo-newbrand2022-top-nav.png' and @alt = 'Katalon']</value>
      <webElementGuid>145c2824-e037-45f7-8ac8-82e0def4db04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
